### ISSUE TITLE
Peer Review - ToDoList Testing

### ISSUE THREAD

**Issue by frempongdev** [chepkok3/To-Do-List#11]
https://github.com/chepkok3/To-Do-List/blob/fbc986aadc05dbf2f2a63a333c8b67e9ca349675/src/modules/addRemoveItems.js#L22-L24

Great use of conditional statements in the function to make your function work per the test requirements 💯 , However, it is advisable to refactor your code or make use of jest mocking for impure functions and DOM instances. ♻️ . This ensures readability and makes your code understandable by other developers. 👍🏿 

Kindly refer to this [Jest Documentation](https://jestjs.io/docs/mock-function-api/) for documentation on how to use mock to make your tests functional. 🧰

**Comment by chepkok3** [comment]
@chepkok3 Changes have been made. Thanks for the comments.
