### ISSUE TITLE
Peer to peer code review: 26-01-2023

### ISSUE THREAD

**Issue by BB-Simon** [chepkok3/To-Do-List#4]
Hi @chepkok3 
Everything looks awesome, however, we have some recommendations that will make your code nicer, as below:
1. You can add `mode` on your web pack config file which defines the more of your server, FYI, it has two modes, 1.`development 2.`production`
2. You can set up the `devServer` property with the `static` property which will take the `dist` folder as it's value

**Comment by chepkok3** [comment]
Changes applied
